### PR TITLE
Add Documentation Section to Project

### PR DESCRIPTION
**Pull request by samuelcmace**
I'm thinking that maybe you guys can write some comments in the Markdown files in this branch as we go along completing the project. I can then generate a report that incorporates your thoughts and learning experiences using the Markdown files that you provide. Do you guys have any thoughts on this?

### CODE REVIEW

**Comment by samuelcmace** [comment]
Markdown files are written in plan text along with your source code. If you want to add any formatting, you can do so with their [simple syntax](https://www.markdownguide.org). We can always use another tool for doing the report and presentation if you would like, but I think this would be the simplest given that we only have a couple of weeks left in the project and still need to deliver a working codebase. Does anyone have any thoughts or concerns on this?

**Review by bibeshpyakurel — APPROVED** [review]
Well organized. I appreciate your work.

**Comment by samuelcmace** [comment]
Do we want to take this approach to note taking or should we take individual notes as we go and coordinate with @bibeshpyakurel to create the actual report/presentation? If so, I can close this branch and corresponding pull request.

**Review by Derek-Waddick — APPROVED** [review]

**Comment by samuelcmace** [comment]
I'm closing this branch, since we're not actively using this.

**Pull request closed without merging**
